import os
from datetime import datetime, timezone

import requests
from dotenv import load_dotenv

load_dotenv()

GITHUB_TOKEN = os.environ["TARGET_GITHUB_TOKEN"].strip()
HF_TOKEN = os.environ["HF_TOKEN"].strip()

TARGET_REPO = os.getenv(
    "TARGET_REPO",
    "leeony2636/docker-fastapi-sentiment-api",
)

GITHUB_API = "https://api.github.com"
HF_API = (
    "https://router.huggingface.co/hf-inference/models/"
    "HuggingFaceTB/SmolLM2-1.7B-Instruct"
)

github_headers = {
    "Accept": "application/vnd.github+json",
    "Authorization": f"Bearer {GITHUB_TOKEN}",
    "X-GitHub-Api-Version": "2022-11-28",
}

hf_headers = {
    "Authorization": f"Bearer {HF_TOKEN}",
    "Content-Type": "application/json",
}


def get_recent_pull_requests():
    url = f"{GITHUB_API}/repos/{TARGET_REPO}/pulls"
    params = {
        "state": "all",
        "sort": "updated",
        "direction": "desc",
        "per_page": 10,
    }

    response = requests.get(
        url,
        headers=github_headers,
        params=params,
        timeout=30,
    )
    response.raise_for_status()
    return response.json()


def get_recent_commits():
    url = f"{GITHUB_API}/repos/{TARGET_REPO}/commits"
    params = {"per_page": 15}

    response = requests.get(
        url,
        headers=github_headers,
        params=params,
        timeout=30,
    )
    response.raise_for_status()
    return response.json()


def build_project_summary(pull_requests, commits):
    lines = [
        f"분석 대상 저장소: {TARGET_REPO}",
        "",
        "최근 Pull Request:",
    ]

    if pull_requests:
        for pr in pull_requests:
            lines.append(
                f"- #{pr['number']} {pr['title']} "
                f"({pr['state']})"
            )
    else:
        lines.append("- 최근 Pull Request 없음")

    lines.extend(["", "최근 커밋:"])

    if commits:
        for commit in commits:
            message = commit["commit"]["message"].split("\n")[0]
            lines.append(f"- {message}")
    else:
        lines.append("- 최근 커밋 없음")

    return "\n".join(lines)


def request_huggingface_analysis(project_summary):
    prompt = f"""
You are a software project reviewer.

Analyze the following GitHub project activity and create a concise weekly report.

Your report must include:
1. Summary of recent changes
2. Positive progress
3. Possible improvements
4. Three recommended next tasks

Use clear Markdown headings.
Do not invent details that are not present in the data.

Project activity:
{project_summary}
""".strip()

    payload = {
        "inputs": prompt,
        "parameters": {
            "max_new_tokens": 700,
            "temperature": 0.2,
            "return_full_text": False,
        },
    }

    response = requests.post(
        HF_API,
        headers=hf_headers,
        json=payload,
        timeout=120,
    )

    if response.status_code != 200:
        raise RuntimeError(
            f"Hugging Face API 오류 "
            f"{response.status_code}: {response.text[:1000]}"
        )

    result = response.json()

    if isinstance(result, list) and result:
        return result[0]["generated_text"].strip()

    if isinstance(result, dict) and "generated_text" in result:
        return result["generated_text"].strip()

    return str(result)


def create_github_issue(report):
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    title = f"Weekly Project Review - {today}"

    body = f"""# Weekly Project Review

- Repository: `{TARGET_REPO}`
- Generated at: {today} UTC
- Generated by: Hugging Face Inference API

---

{report}

---

This report was generated automatically by
`github-weekly-project-reviewer`.
"""

    url = f"{GITHUB_API}/repos/{TARGET_REPO}/issues"
    payload = {
        "title": title,
        "body": body,
    }

    response = requests.post(
        url,
        headers=github_headers,
        json=payload,
        timeout=30,
    )
    response.raise_for_status()

    issue = response.json()
    print(f"Created GitHub Issue: {issue['html_url']}")


def main():
    pull_requests = get_recent_pull_requests()
    commits = get_recent_commits()

    project_summary = build_project_summary(
        pull_requests,
        commits,
    )

    report = request_huggingface_analysis(project_summary)
    create_github_issue(report)


if __name__ == "__main__":
    main()